version: '3'

tasks:
  default:
    cmds:
      - task: dockerdev-up
  dockerdev-up:
    aliases:
      - dev-up
    desc: "Run development environment with Docker Compose"
    cmds:
      - echo "Starting dev environment..."
      - docker compose -f ./deployments/docker-compose.dev.yml build 

  dockerdev-no-cache-up:
    aliases:
      - build-no-cache
    desc: "Building development environment with Docker Compose"
    cmds:
      - echo "Building dev environment..."
      - docker compose -f ./deployments/docker-compose-dev.yml build --no-cache 

  dockerdev-down:
    aliases:
      - dev-down
    desc: "Stop development environment"
    cmds:
      - echo  "Stopping dev environment..."
      - docker compose -f ./deployments/docker-compose-dev.yml down